// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twkbmlkoxhzqppqjtnmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3a2JtbGtveGh6cXBwcWp0bm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTE3MTQsImV4cCI6MjA2Mzk2NzcxNH0.Dsqhnk8NtvAnzyYk6sCGMvKrMN2iDEKbQy8SJNGRiag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);